package org.mobile.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import org.mobile.db.BrandInfo;
import org.mobile.db.MobileSaleInfo;

import org.mobile.db.BrandInfoDao;
import org.mobile.db.MobileSaleInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig brandInfoDaoConfig;
    private final DaoConfig mobileSaleInfoDaoConfig;

    private final BrandInfoDao brandInfoDao;
    private final MobileSaleInfoDao mobileSaleInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        brandInfoDaoConfig = daoConfigMap.get(BrandInfoDao.class).clone();
        brandInfoDaoConfig.initIdentityScope(type);

        mobileSaleInfoDaoConfig = daoConfigMap.get(MobileSaleInfoDao.class).clone();
        mobileSaleInfoDaoConfig.initIdentityScope(type);

        brandInfoDao = new BrandInfoDao(brandInfoDaoConfig, this);
        mobileSaleInfoDao = new MobileSaleInfoDao(mobileSaleInfoDaoConfig, this);

        registerDao(BrandInfo.class, brandInfoDao);
        registerDao(MobileSaleInfo.class, mobileSaleInfoDao);
    }
    
    public void clear() {
        brandInfoDaoConfig.getIdentityScope().clear();
        mobileSaleInfoDaoConfig.getIdentityScope().clear();
    }

    public BrandInfoDao getBrandInfoDao() {
        return brandInfoDao;
    }

    public MobileSaleInfoDao getMobileSaleInfoDao() {
        return mobileSaleInfoDao;
    }

}
