package org.mobile.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MOBILE_SALE_INFO".
 */
public class MobileSaleInfo {

    private Long id;
    private String brandNum;
    private String model;
    private String barCode;
    private String modelStorage;
    private String objectId;
    private java.util.Date date;

    public MobileSaleInfo() {
    }

    public MobileSaleInfo(Long id) {
        this.id = id;
    }

    public MobileSaleInfo(Long id, String brandNum, String model, String barCode, String modelStorage, String objectId, java.util.Date date) {
        this.id = id;
        this.brandNum = brandNum;
        this.model = model;
        this.barCode = barCode;
        this.modelStorage = modelStorage;
        this.objectId = objectId;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBrandNum() {
        return brandNum;
    }

    public void setBrandNum(String brandNum) {
        this.brandNum = brandNum;
    }

    public String getModel() {
        return model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public String getBarCode() {
        return barCode;
    }

    public void setBarCode(String barCode) {
        this.barCode = barCode;
    }

    public String getModelStorage() {
        return modelStorage;
    }

    public void setModelStorage(String modelStorage) {
        this.modelStorage = modelStorage;
    }

    public String getObjectId() {
        return objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
